### PR TITLE
dark mode, added blockies

### PR DESCRIPTION
**Pull request by corvardt**

### CODE REVIEW

**Comment by bradthomasbrown** [comment]
image
image

were you able to get the blockies pngs to render? i get a strange error that i've tried fairly hard to debug but looks internal to the module and no image

**Comment by corvardt** [comment]
edit: node_modules/pnglib/pnglib.js should be fine, the issue is node_modules/ethereum-blockies-base64/dist/**main.js**

**Comment by corvardt** [comment]
if error still pops then node_modules/ethereum-blockies-base64/dist/**main.js** is the culprit, change it to following and it should work: 

[main.js.txt](https://github.com/bradbrown-llc/dizzyhavoc-web/files/14733644/main.js.txt)

**Comment by corvardt** [comment]
Also yes, blockie should render quickly and update whenever selected address changes!

**Comment by corvardt** [comment]
recreated the issue: 
original main.js @node_modules/ethereum-blockies-base64/dist/main.js
Capture d'écran 2024-03-23 232254
changed main.js with
[main.js.txt](https://github.com/bradbrown-llc/dizzyhavoc-web/files/14733767/main.js.txt)
 V
 Capture d'écran 2024-03-23 232454

**Comment by corvardt** [comment]
the strange thing being, when I import the repo from my git and run it without the modif it works

**Comment by corvardt** [comment]
It could also be the corresponding .deno/pnglib|ethereum-blockies-base64 folders

**Comment by corvardt** [comment]
Tried but couldn't replicate the issue

**Pull request merged**
